# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XiondAT1900 < Formula
  desc "Xiond is the Cosmos SDK based blockchain cli/daemon for the Xion Network."
  homepage "https://xion.burnt.com/"
  version "19.0.0"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/burnt-labs/xion/releases/download/v19.0.0/xiond_19.0.0_darwin_amd64.tar.gz"
      sha256 "1bf10d377f1b1436c25eea46a8a2daee67236cdebf467f48d946ffb3c37cd34b"

      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/burnt-labs/xion/releases/download/v19.0.0/xiond_19.0.0_darwin_arm64.tar.gz"
      sha256 "5725262b7bcb45fd1bb0da579f8cfb5479c064527c54db8729c887a2759e2023"

      def install
        bin.install "xiond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v19.0.0/xiond_19.0.0_linux_amd64.tar.gz"
      sha256 "a735625f5b63cf9ddea1c6dda4365457085c1d2a8011049d097c79b0371bfba0"
      def install
        bin.install "xiond"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/burnt-labs/xion/releases/download/v19.0.0/xiond_19.0.0_linux_arm64.tar.gz"
      sha256 "4bc8721d83100de481c13fea7f6279f860cb41de43d4a11c4115db6d34b22148"
      def install
        bin.install "xiond"
      end
    end
  end

  test do
    system "#{bin}/xiond version"
  end
end
